[functions."ahgora-clock-0900"]
  schedule = "58 11 * * *"

[functions."ahgora-clock-1200"]
  schedule = "58 14 * * *"

[functions."ahgora-clock-1215"]
  schedule = "13 15 * * *"

[functions."ahgora-clock-1515"]
  schedule = "13 18 * * *"
